services:
  dev-container:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/workspaces:cached
    command: 'sleep infinity'
    environment:
      - HOST=0.0.0.0 # Necesario para que Vite escuche fuera del contenedor
      - CHOKIDAR_USEPOLLING=true # Activa el hot reload de React
    ports:
      - '5173:5173'
      - '3000:3000'
    networks:
      - mi-red # Conectar a la misma red para que se puedan comunicar
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - mi-red # Conectar a la misma red para que se puedan comunicar
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1']

volumes:
  postgres-data:

networks:
  mi-red:
    driver: bridge
